apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyllama-interface
  labels:
    app: tinyllama-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyllama-interface
  template:
    metadata:
      labels:
        app: tinyllama-interface
    spec:
      containers:
      - name: tinyllama-interface
        image: tinyllama-interface:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: FLASK_ENV
          value: "production"
        - name: TINYLLAMA_SERVICE_HOST
          value: "tinyllama-service"
        - name: TINYLLAMA_SERVICE_PORT
          value: "8000"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: tinyllama-interface-service
spec:
  selector:
    app: tinyllama-interface
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer 